# Конфигурация плагина для WSGI развертывания

# Основные настройки
DEBUG = false
SECRET_KEY = "change-me-in-production"

# BILLmanager API
BILLMGR_API_URL = "https://localhost:1500/billmgr"
BILLMGR_API_USE_INTERFACE = ""
FORWARDED_SECRET = "SECRET_FROM_BILLMGR_CONF"

# База данных
DB_HOST = "localhost"
DB_PORT = 3306
DB_USER = "billmgr"
DB_PASSWORD = "password"
DB_NAME = "billmgr"

# Логирование для продакшена
LOG_LEVEL = "INFO"
LOG_FILE = "/var/log/billmgr-plugin/app.log"

# Настройки для высокой нагрузки
REQUEST_TIMEOUT = 300
MAX_CONTENT_LENGTH = 16777216  # 16MB

# Кеширование (если используется Redis)
# REDIS_URL = "redis://localhost:6379/0"
# CACHE_TTL = 300

# Настройки безопасности
ALLOWED_HOSTS = ["plugin.example.com", "localhost"]
CORS_ORIGINS = []